###
POST http://localhost:9001/api/rol  HTTP/1.1
Content-Type: application/json

{
    "rol":2,
    "nombre":"Cocinero"
}

###
GET http://localhost:9001/api/Rol HTTP/1.1

###
GET http://localhost:9001/api/rol/673ac6ea2c316c643263290c HTTP/1.1

###
PUT  http://localhost:9001/api/Rol/673ac70f2c316c643263290e HTTP/1.1
Content-Type: application/json

{
    "rol": 3,
    "nombre":"Mesero"
}
###
DELETE http://localhost:9001/api/Rol/673abf558564a0a51bb1851f HTTP/1.1