###
POST  http://localhost:9001/api/cat_productos HTTP/1.1
Content-Type: application/json

{
  "nombre":"Carnicos"
}

###
GET  http://localhost:9001/api/cat_productos HTTP/1.1

###
GET  http://localhost:9001/api/cat_producto/673bfa3ac68287d18b1fd282 HTTP/1.1
###

PUT  http://localhost:9001/api/cat_producto/673bfa3ac68287d18b1fd282 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Pescado"
}

###
DELETE http://localhost:9001/api/cat_productos/673bfa3ac68287d18b1fd282 HTTP/1.1