###
POST  http://localhost:9001/api/facturas HTTP/1.1
Content-Type: application/json

{
  "nombre":"Eduardo",
  "celular":3124652545,
  "valor":50000,
  "correo":"ejemplo@gmail.com",
  "Pedidos":"673aceb8168af76b6c9fa34e" 
}

###
GET  http://localhost:9001/api/facturas HTTP/1.1

###
GET  http://localhost:9001/api/facturas/673ad010ec4faa747f9378de HTTP/1.1
###

PUT  http://localhost:9001/api/facturas/673acfddec4faa747f9378da HTTP/1.1
Content-Type: application/json

{
  "nombre": "Mariana",
  "celular": 3217894560,
  "valor": 75000,
  "correo": "mariana123@gmail.com",
  "Pedidos": "673aceb8168af76b6c9fa34e"
}

###
DELETE http://localhost:9001/api/facturas/673acfddec4faa747f9378da HTTP/1.1